package com.nagarro.locators;

import com.nagarro.utils.Common;

public enum Home {
	SEARCH_BUS_ORIGIN("SEARCH_BUS_ORIGIN"),
	SEARCH_BUS_DESTINATION("SEARCH_BUS_DESTINATION"),
	SEARCH_BUS_ONWARD_DATE_LABEL("SEARCH_BUS_ONWARD_DATE_LABEL"),
	SEARCH_BUS_ONWARD_DATE_ACTIVE_CALENDAR("SEARCH_BUS_ONWARD_DATE_ACTIVE_CALENDAR"),
	SEARCH_BUS_ONWARD_DATE_INACTIVE_CALENDAR("SEARCH_BUS_ONWARD_DATE_INACTIVE_CALENDAR"),
	SEARCH_BUS_RETURN_DATE_LABEL("SEARCH_BUS_RETURN_DATE_LABEL"),
	SEARCH_BUS_RETURN_DATE_ACTIVE_CALENDAR("SEARCH_BUS_RETURN_DATE_ACTIVE_CALENDAR"),
	SEARCH_BUS_RETURN_DATE_INACTIVE_CALENDAR("SEARCH_BUS_RETURN_DATE_INACTIVE_CALENDAR"),
	SEARCH_BUS_CALENDAR_NEXT_MONTH("SEARCH_BUS_CALENDAR_NEXT_MONTH"),
	SEARCH_BUS_CALENDAR_PREVIOUS_MONTH("SEARCH_BUS_CALENDAR_PREVIOUS_MONTH"),
	SEARCH_BUS_CALENDAR_DAY("SEARCH_BUS_CALENDAR_DAY"),
	SEARCH_BUS_MONTH_TITLE("SEARCH_BUS_MONTH_TITLE"),
	SEARCH_BUS_BUTTON("SEARCH_BUS_BUTTON"),
	LINK_HOTELS("LINK_HOTELS"),
	LINK_BUSES("LINK_BUSES"),
	TEXT_OPTIONAL("TEXT_OPTIONAL"),
	SELECTED_CITY("SELECTED_CITY"),
	SEARCH_BUS_ORIGIN_ERROR("SEARCH_BUS_ORIGIN_ERROR"),
	SEARCH_BUS_DESTINATION_ERROR("SEARCH_BUS_DESTINATION_ERROR"),
	LINK_ABOUT_US("LINK_ABOUT_US");

	String locator;

	Home(String locator) {
		this.locator = locator;
	}

	public String value() {
		return Common.getConfig("locators" + System.getProperty("file.separator") + "HomePage").getString(this.locator);
	}
}
